version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit_main
    hostname: rmq
    ports:
      - 3000:5672
      - 13000:15672
    environment:
      - RABBITMQ_ERLANG_COOKIE="3@dj4z#yWjW0"
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
